version: '3.8'
services:
  postgres:
    image: postgres:16.4
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ocorrenciaapi
    ports:
      - "9090:5432"